FROM php:7.2-fpm

RUN apt-get update -qq

RUN apt-get update && apt-get install -y \
#  build-essential \
  cron \
  libfreetype6-dev \
  libicu-dev \
  libgd-dev \
  libjpeg62-turbo-dev \
#  libmcrypt-dev \
  libpng-dev \
  libxslt1-dev \
  mariadb-client \
  libonig-dev \
  zip \
  libzip-dev \
  git \
  procps \
  unzip

RUN docker-php-ext-install \
  bcmath \
  gd \
  intl \
  mbstring \
#  mcrypt \
  opcache \
  pdo_mysql \
  soap \
  xsl \
  sockets \
  zip

RUN docker-php-ext-enable sockets

RUN curl -sS https://getcomposer.org/installer | \
  php -- --install-dir=/usr/local/bin --filename=composer

ENV PHP_MEMORY_LIMIT 2G
ENV PHP_PORT 9000
ENV PHP_PM dynamic
ENV PHP_PM_MAX_CHILDREN 10
ENV PHP_PM_START_SERVERS 4
ENV PHP_PM_MIN_SPARE_SERVERS 2
ENV PHP_PM_MAX_SPARE_SERVERS 6
ENV APP_MAGE_MODE default

RUN cd /usr/local/etc/php/conf.d/ && \
  echo 'memory_limit = -1' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

WORKDIR /project

RUN apt-get install -y telnet
RUN apt-get install -y vim

# RUN usermod -u 1000 www-data

RUN chown -R root:www-data /project
RUN chmod u+rwx,g+rx,o+rx /project
RUN find /project -type d -exec chmod u+rwx,g+rx,o+rx {} +
RUN find /project -type f -exec chmod u+rw,g+rw,o+r {} +

RUN pecl install xdebug \
  && docker-php-ext-enable xdebug