<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> <?php echo $title ?? 'Admin' ?> </title>
</head>
<body>
        
    <div class="container">
        <form action="/admin/authenticate" method="post">
            <div class="form-roup">
                <label for="username">Usuário:</label>
                <input type="text" id="username" name="username">
            </div>

            <div class="form-roup">
                <label for="password">Senha:</label>
                <input type="password" id="password" name="password">
            </div>

            <div class="form-group">
                <button type="submit">Entrar</button>
            </div>
        </form>
    </div>

</body>
</html>