version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/vitor/Projects/bis2bis/code:/project"
      - "./nginx/sites-enabled/conf:/etc/nginx/conf.d"
    links:
      - php
    networks:
      bis2bis_teste:
        ipv4_address: 198.25.1.2
  php:
    build: ./php
    volumes:
      - "/home/vitor/Projects/bis2bis/code:/project"
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      bis2bis_teste:
        ipv4_address: 198.25.1.3
    extra_hosts:
      - "dev.rabbitmq.com.br:198.25.1.4"
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql/dump.sql:/tmp/dump.sql
    networks:
      bis2bis_teste:
        ipv4_address: 198.25.1.5
networks:
  bis2bis_teste:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 198.25.1.0/16